systemtap: fix error: 'EM_AARCH64' was not declared in this scope
bump SRCREV to commit 508059f04842ed85d10bfbec8a9c688d57368860
 Define EM_AARCH64 if elf.h doesn't.

Change-Id: I17b84999d6cdbae8ac32d408c75a910eb94a961c
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>