optee-os: fix build failure with GCC 6
Add NOWERROR=1 to disable errors introduced with the upgrade to GCC 6:
error: dereferencing type-punned pointer might break strict-aliasing rules
[-Werror=strict-aliasing]

Change-Id: Ibf95883c1fb105dc661cede5311beddd02ddd4c1
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>