external-arm-toolchain: fix oe_multilib_header() errors
Since external toolchain doesn't provide multilib support so define
oe_multilib_header() as an empty function to avoid errors such as:

ERROR: external-arm-toolchain-2019.03-r0 do_install: oe_multilib_header: Unable to find header bits/procfs-id.h.
ERROR: external-arm-toolchain-2019.03-r0 do_install: oe_multilib_header: Unable to find header bits/procfs.h.
ERROR: external-arm-toolchain-2019.03-r0 do_install: oe_multilib_header: Unable to find header bits/shmlba.h.

Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
Change-Id: I8ae41de962d72162f2ae47c419407b6eadaf8c12