binutils: upgrade to linaro binutils 2.25.1-2016.10ish
* switch to git, add SRCREV, update S dir
* update version to 2.25.1-2016.10 (not tagged officially)
* remove gdb directory from the source to avoid building it
  and trigger undefined reference to `PyUnicodeUCS4_Decode'

Change-Id: Ib94da6699c86345a444e1a2684f7fec7f6457e4a
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>