meta-ilp32: glibc: use arm/ilp32 branch for 2.26
Interim patches for ILP32 (1 and 2) are not needed anymore.
One patch from upstream has been removed (0026) because it's
now included in this version of Git, and another (from
upstream as well) has been added (include-string.h) in order
to fix this:

  | ../sysdeps/unix/sysv/linux/gentempfd.c: In function '__gen_tempfd':
  | ../sysdeps/unix/sysv/linux/gentempfd.c:28:36: error: implicit declaration of function 'strcmp' [-Werror=implicit-function-declaration]
  |    if (fd < 0 && errno == ENOENT && strcmp (P_tmpdir, "/tmp") != 0)
  |                                     ^~~~~~

Change-Id: If9d7f71212845fd8b06536691c970c3875765d24
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>